In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from scipy import stats

In [2]:
df=pd.read_csv("Jamboree_Admission.csv")

In [3]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [5]:
for i in df.columns:
    print(i,':',df[i].nunique ())

Serial No. : 500
GRE Score : 49
TOEFL Score : 29
University Rating : 5
SOP : 9
LOR  : 9
CGPA : 184
Research : 2
Chance of Admit  : 61


In [6]:
for i in df.columns:
    print(i,":",df[i].value_counts())

Serial No. : 1      1
330    1
343    1
342    1
341    1
      ..
162    1
161    1
160    1
159    1
500    1
Name: Serial No., Length: 500, dtype: int64
GRE Score : 312    24
324    23
316    18
321    17
322    17
327    17
311    16
320    16
314    16
317    15
325    15
315    13
308    13
323    13
326    12
319    12
313    12
304    12
300    12
318    12
305    11
301    11
310    11
307    10
329    10
299    10
298    10
331     9
340     9
328     9
309     9
334     8
332     8
330     8
306     7
302     7
297     6
296     5
295     5
336     5
303     5
338     4
335     4
333     4
339     3
337     2
290     2
294     2
293     1
Name: GRE Score, dtype: int64
TOEFL Score : 110    44
105    37
104    29
107    28
106    28
112    28
103    25
100    24
102    24
99     23
101    20
111    20
108    19
113    19
109    19
114    18
116    16
115    11
118    10
98     10
119    10
120     9
117     8
97      7
96      6
95      3
93      2
94      2
92      1
Name: TO

In [7]:
for i in df.columns:
    print(i,":",df[i].isnull().sum())

Serial No. : 0
GRE Score : 0
TOEFL Score : 0
University Rating : 0
SOP : 0
LOR  : 0
CGPA : 0
Research : 0
Chance of Admit  : 0


In [8]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

            LOR         CGPA    Research  Chance of Admit   
count  500.00000  500.000000  500.000000         500.00000  
mean     3.48400    8.576440    0.560000           0.72174  
std      0.92545    0.604813    0.496884           0.14114  
min      1.00000    6.800000    0.000000           0.34000  
25%      3.00000    8.127500    0.000000           0.63000  
50%      3.50000    8.560000    1.000000           0.72000  
75%      4.00000    9.040000    1.000000           0.82000  
max      5.00000    9.920000    1.000000           0.97000

In [12]:
df.shape

(500, 9)

In [13]:
df.dtypes

Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [16]:
df1=df.set_index('Serial No.')

In [17]:
df1

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
496               332          108                  5  4.5   4.0  9.02   
497               337          117                  5  5.0   5.0  9.87   
498               330          120                  5  4.5   5.0  9.56   
499               312          103                  4  4.0   5.0  8.43   
500               327          113                  4  4.5   4.5  9.04   

            Research  Chance of Admit   
Serial No.                              
1                  1              0.92  
2                  1              0.76  
3                  1              0.72  
4                  1              0.80  
5                  0              0.65  
...              ...               ...  
496                1              0.87  
497                1              0.96  
498                1              0.93  
499                0              0.73  
500                0              0.84  

[500 rows x 8 columns]

## Standardisation

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(df1)

x_std=scaler.transform(df1)
x=pd.DataFrame(x_std,columns=['GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research','Chance of Admit'])                                 


In [19]:
x

GRE Score  TOEFL Score  University Rating       SOP       LOR      CGPA  \
0     1.819238     1.778865           0.775582  1.137360  1.098944  1.776806   
1     0.667148    -0.031601           0.775582  0.632315  1.098944  0.485859   
2    -0.041830    -0.525364          -0.099793 -0.377773  0.017306 -0.954043   
3     0.489904     0.462163          -0.099793  0.127271 -1.064332  0.154847   
4    -0.219074    -0.689952          -0.975168 -1.387862 -0.523513 -0.606480   
..         ...          ...                ...       ...       ...       ...   
495   1.376126     0.132987           1.650957  1.137360  0.558125  0.734118   
496   1.819238     1.614278           1.650957  1.642404  1.639763  2.140919   
497   1.198882     2.108041           1.650957  1.137360  1.639763  1.627851   
498  -0.396319    -0.689952           0.775582  0.632315  1.639763 -0.242367   
499   0.933015     0.955926           0.775582  1.137360  1.098944  0.767220   

     Research  Chance of Admit  
0    0.886405         1.406107  
1    0.886405         0.271349  
2    0.886405        -0.012340  
3    0.886405         0.555039  
4   -1.128152        -0.508797  
..        ...              ...  
495  0.886405         1.051495  
496  0.886405         1.689797  
497  0.886405         1.477030  
498 -1.128152         0.058582  
499 -1.128152         0.838728  

[500 rows x 8 columns]

In [20]:
y=x['Chance of Admit']

In [21]:
w=x.drop('Chance of Admit',axis=1)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
w_train,w_test,y_train,y_test=train_test_split(w,y,train_size=0.7,random_state=100)

In [24]:
w_train

GRE Score  TOEFL Score  University Rating       SOP       LOR      CGPA  \
153   0.667148    -0.360777          -0.099793 -0.377773  0.558125  0.287252   
84    2.085104     1.285102           1.650957  1.137360  1.098944  1.445794   
310   0.312659    -0.525364          -0.099793 -0.377773  0.017306  0.270702   
494  -1.371164    -1.348304          -0.099793 -0.882817 -1.605151 -0.209266   
126   0.578526     0.955926          -0.099793  0.632315 -0.523513  1.230636   
..         ...          ...                ...       ...       ...       ...   
343  -1.016674    -0.689952          -0.975168 -0.882817  0.017306 -0.738885   
359   0.401282    -0.031601          -0.975168 -1.387862 -2.145970 -0.225816   
323  -1.016674    -0.854540          -0.975168 -1.387862 -1.064332 -0.656132   
280  -0.484941    -0.854540          -0.099793  1.137360  0.558125  0.105196   
8    -1.282541    -0.854540          -1.850542 -1.387862 -2.145970 -0.954043   

     Research  
153 -1.128152  
84   0.886405  
310  0.886405  
494  0.886405  
126  0.886405  
..        ...  
343 -1.128152  
359 -1.128152  
323 -1.128152  
280  0.886405  
8   -1.128152  

[350 rows x 7 columns]

In [25]:
w_test

GRE Score  TOEFL Score  University Rating       SOP       LOR      CGPA  \
69    1.021637     1.285102           0.775582  1.137360  0.558125  0.965827   
29   -0.573563    -1.348304          -0.975168 -1.892906 -1.605151 -2.112585   
471  -0.484941    -0.689952          -0.099793 -1.387862  0.558125 -0.805087   
344  -1.902897    -1.842067          -0.975168 -1.892906 -1.605151 -2.046382   
54    0.489904     0.462163          -0.099793 -0.377773  0.017306 -0.954043   
..         ...          ...                ...       ...       ...       ...   
308  -0.396319     0.132987          -0.099793  0.127271 -0.523513 -0.076861   
171   1.553371     1.614278           1.650957  0.632315  1.098944  0.816871   
457  -1.902897    -1.348304          -1.850542 -1.387862 -2.145970 -1.665719   
75    1.110260     1.120514          -0.975168 -1.387862  0.558125 -0.027209   
311   1.021637     0.132987           0.775582  1.137360  0.558125  0.998928   

     Research  
69   0.886405  
29  -1.128152  
471 -1.128152  
344 -1.128152  
54  -1.128152  
..        ...  
308 -1.128152  
171  0.886405  
457 -1.128152  
75   0.886405  
311  0.886405  

[150 rows x 7 columns]

In [26]:
y_train

153    0.484116
84     1.547952
310    0.271349
494   -0.296030
126    0.909651
         ...   
343   -0.934332
359    0.625961
323   -0.721564
280   -0.296030
8     -1.572633
Name: Chance of Admit, Length: 350, dtype: float64

In [27]:
y_test

69     0.413194
29    -1.288944
471   -0.579720
344   -1.785400
54    -0.154185
         ...   
308   -0.225108
171    1.193340
457   -2.494624
75    -0.012340
311    0.838728
Name: Chance of Admit, Length: 150, dtype: float64

In [28]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [29]:
model.fit(w_train,y_train)

LinearRegression()

In [31]:
w=model.coef_
w

array([0.090411  , 0.15138317, 0.04242884, 0.00388195, 0.11296889,
       0.54621902, 0.09713738])

In [32]:
np.reshape(w,(1,7))

array([[0.090411  , 0.15138317, 0.04242884, 0.00388195, 0.11296889,
        0.54621902, 0.09713738]])

In [33]:
w0=model.intercept_
w0

-0.024866812538764868

In [36]:
y_hat=model.predict(w_test)
y_hat[:5]

array([ 0.97607234, -1.77440902, -0.66906869, -1.9331819 , -0.54505807])

In [38]:
y[:5]

0    1.406107
1    0.271349
2   -0.012340
3    0.555039
4   -0.508797
Name: Chance of Admit, dtype: float64

In [39]:
model.score(w_train,y_train)

0.8132510822066584

In [41]:
columns=np.array(w_train.columns)
for i in range(7):
    print(columns[i],":",w[i])


GRE Score : 0.09041100444228009
TOEFL Score : 0.15138316913460392
University Rating : 0.0424288418292271
SOP : 0.003881950858450026
LOR : 0.11296889349260134
CGPA : 0.5462190201662886
Research : 0.09713738365964285


### CGPA have high feature importance than others

## Multicollinearity check by VIF score(variables are dropped one-by-one till none has VIF>5)

Consider 'GRE Score' as dependent column

In [42]:
def multi_colinear():
    vif_1st=[]
    for i in w_train.columns:
         x1=w_train[i].values
         x2=w_train.drop(i,axis=1)
         x2=x2.values
         model.fit(x2,x1)
         x1_hat=model.predict(x2)
         den=sum(((x1-x1.mean())**2))
         num=sum((x1-x1_hat)**2)
         score=1-(num/den)
         vif=1/(1-(score)**2)
         vif_1st.append(vif)
    return vif_1st

In [43]:
multi_colinear()

[2.658533832166762,
 2.152099820799423,
 1.5540959305762307,
 1.6726682859991662,
 1.3201148552293482,
 2.632332704352941,
 1.1201228430478483]

VIF values of all columns has less then 5 it is not multi colinear

### Check the mean of residuals is nearly zero

In [48]:
y_hat=np.dot(w,np.transpose(w_train))+w0


In [49]:
y_hat.shape

(350,)

In [50]:
residuals=y_train-y_hat
residuals.mean()


-1.490870918782353e-17